# docker-compose
# author: dreamlu
# github.com/dreamlu
version: '3'
services:
  # mysql-server
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/dreamlu/mysql:8.0
    environment:
      MYSQL_DATABASE: micro-go
      MYSQL_USER: wobangkj
      MYSQL_PASSWORD: wobangkj
      MYSQL_ROOT_PASSWORD: wobangkj
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    ports:
      - 3378:3306
    restart: always
    # sql备份目录
    volumes:
      #      - /root/bak/mysql:/bak
      - /root/micro-go/bak/mysql/data:/var/lib/mysql
    networks:
      - micro-go
  #   redis
  redis:
    image: redis:4.0
    ports:
      - 6378:6379
    #container_name: d-redis
    restart: always
    networks:
      - micro-go
  # consul
  consul:
    image: consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 54:53/udp
    restart: always
    networks:
      - micro-go
  # api gateway
  api-gateway:
    image: registry.cn-hangzhou.aliyuncs.com/dreamlu/common:micro-go-api-gateway-1.0
    ports:
      - 9000:9000
    restart: always
    command: ./main --server_name api-gateway api --address=0.0.0.0:9000 --namespace=micro-go.api --handler=http
    networks:
      - micro-go
  # base micro-go service
  micro-go:
    image: registry.cn-hangzhou.aliyuncs.com/dreamlu/common:micro-go-base-srv-1.0
    #container_name: d-demo
    restart: always
    volumes:
      - /root/micro-go/bak/static:/static
      - /root/micro-go/bak/log:/log
    networks:
      - micro-go
  # 监控
  cadvisor:
    image: google/cadvisor:latest
    ports:
    - 8080:8080
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - micro-go

networks:
  micro-go:
    driver: bridge